### ISSUE TITLE
make test/test_SM_npointfunctions.x runs the the .meta code twice.

### ISSUE THREAD

**Issue by iolojz** [iolojz/FlexibleSUSY#7]
This is some dependency issue. Or maybe test/test_SM_npointfunctions.cpp.in is touched by Mathematica's OpenRead[]... Investigate!

**Comment by iolojz** [comment]
This seems to be an issue with the $(LIBSM) dependency. Is there maybe a conflict between models/SM and model_specific/SM?

**Comment by iolojz** [comment]
Somehow the .cpp file gets generated by just typing `make`. This generates no binary however... Something is fishy

**Comment by Expander** [comment]
`$(LIBSM)` denotes the compiled SM-library (`models/SM/libSM.a` or `models/SM/libSM.so`). So, the problem may be, that `$(LIBSM)` somehow changes its time-stamp, which triggers the re-generation of `test/test_SM_npointfunctions.cpp`.  Could that be?

You should in any way replace the dependency of `test/test_SM_npointfunctions.cpp` on `$(LIBSM)` by `$(METACODE_STAMP_SM)`.  Does that help?

**Comment by iolojz** [comment]
Yes, that solved the issue :)
